const $ = (id) => document.getElementById(id);
const state = { files: [], rows: [], charts: {} };
const subjectLabels = { AD: 'Анализ данных', ENGLISH: 'Data Analysis · English', CP: 'Компьютерный практикум', DM: 'Дискретная математика', MAT: 'Математика', M: 'Математика · расширенный срез' };
const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function parseFile(file){
  const n=file.name;
  let subject='Другие данные';
  if(/^English_DA/i.test(n)||/^ENGLISH/i.test(n)) subject=subjectLabels.ENGLISH;
  else if(/^AD/i.test(n)) subject=subjectLabels.AD;
  else if(/^CP/i.test(n)||/^КП/i.test(n)) subject=subjectLabels.CP;
  else if(/^DM/i.test(n)) subject=subjectLabels.DM;
  else if(/^MAT/i.test(n)) subject=subjectLabels.MAT;
  else if(/^M_/i.test(n)) subject=subjectLabels.M;
  const fullYear=(n.match(/(20\d\d)[-–](20\d\d)/)||[])[0];
  const shortYear=(n.match(/(\d\d)[-–](\d\d)/)||[])[0];
  const year=fullYear || (shortYear ? `20${shortYear}` : '—');
  const groupHint=(n.match(/(?:^|[_ ])([12])(?:[_ ]|\(|-)/)||[])[1];
  return {...file, subject, year: year.replace(/^(20\d\d)-/, '$1–20'), groupHint};
}
function numeric(v){ if(v===null||v===undefined||v==='') return null; if(typeof v==='number'&&Number.isFinite(v)) return v; const x=String(v).replace(',','.').trim(); if(!x||x==='-'||x==='—') return null; const n=Number(x.replace(/[^\d.-]/g,'')); return Number.isFinite(n)?n:null; }
function median(a){const b=[...a].sort((x,y)=>x-y); return b.length?b[Math.floor(b.length/2)]:0}
function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function format(n){return Number.isFinite(n)?n.toLocaleString('ru-RU',{maximumFractionDigits:1}):'—'}
function setStatus(text,error=false){$('status').className='status'+(error?' error':''); $('status').innerHTML=error?`⚠ ${esc(text)}`:`<span class="spinner"></span> ${esc(text)}`}
function updateYears(){const s=$('subjectSelect').value; const ys=[...new Set(state.files.filter(f=>f.subject===s).map(f=>f.year))].sort().reverse(); $('yearSelect').innerHTML=ys.map(y=>`<option>${esc(y)}</option>`).join(''); updateGroups();}
function updateGroups(){const s=$('subjectSelect').value,y=$('yearSelect').value;const fs=state.files.filter(f=>f.subject===s&&f.year===y);const groups=[...new Set(fs.flatMap(f=>f.groups||[]))].sort((a,b)=>a.localeCompare(b,'ru')); $('groupSelect').innerHTML='<option value="__all">Все группы</option>'+groups.map(g=>`<option>${esc(g)}</option>`).join('');}
async function loadWorkbook(file){const cached=(window.DATA_CACHE||[]).find(x=>x.name===file.name);if(cached)return {...file,rows:cached.rows,workMax:cached.workMax||[],workOrder:cached.workOrder||[],targetColumns:cached.targetColumns||[]};const res=await fetch(encodeURI('../data/'+file.name)); if(!res.ok) throw Error(`Не удалось загрузить ${file.name}`); const wb=XLSX.read(await res.arrayBuffer(),{type:'array'}); const ws=wb.Sheets[wb.SheetNames[0]]; const data=XLSX.utils.sheet_to_json(ws,{header:1,defval:null}); const headers=(data.shift()||[]).map(v=>String(v??'')); const groupIx=headers.findIndex(h=>/групп|group/i.test(h)); const excluded=headers.map((h,i)=>({h:h.toLowerCase(),i})).filter(({h})=>h.includes('итоговая оценка')||h.includes('последние загруженные из этого курса')).map(x=>x.i); const rows=data.filter(r=>r.some(v=>v!==null&&v!=='-')).map(r=>{const group=String(r[groupIx>=0?groupIx:1]??'Без группы').trim(); const values=r.slice(2).filter((_,i)=>!excluded.includes(i+2)).map(numeric).filter(v=>v!==null); return {group, values, scores:[], target:null, id:String(r[0]??'').slice(0,8)};}).filter(r=>r.values.length); return {...file,headers,rows,workMax:[],workOrder:[],targetColumns:[]};}
async function run(){const subject=$('subjectSelect').value,year=$('yearSelect').value,group=$('groupSelect').value;const files=state.files.filter(f=>f.subject===subject&&f.year===year);setStatus('Читаю Quiz и рассчитываю экзаменационный прогноз…'); try {const loaded=await Promise.all(files.map(loadWorkbook)); state.rows=loaded.flatMap(f=>f.rows.map(r=>({...r,file:f.name,workMax:f.workMax,workOrder:f.workOrder,targetColumns:f.targetColumns}))).filter(r=>group==='__all'||r.group===group); if(!state.rows.length) throw Error('В выбранном срезе нет строк с числовыми оценками.'); render(subject,year,group); $('status').style.display='none'; $('dashboard').hidden=false;}catch(e){setStatus(e.message,true);$('dashboard').hidden=true;}}
function forecastExam(rows){const observed=rows.filter(r=>r.target&&r.target[1]>0);const label=(rows.find(r=>r.targetColumns&&r.targetColumns.length)||{}).targetColumns?.[0]?.label||'экзамен/зачёт';if(observed.length<10)return {label,observed,model:null};const x=observed.map(r=>{const q=(r.scores||[]).map(s=>s[1]).filter(i=>Number.isFinite(i));const p=(r.scores||[]).map(s=>{const mx=r.workMax?.[s[1]]||0;return mx>0?s[0]/mx:null}).filter(v=>v!==null);return p.length?mean(p):0});const y=observed.map(r=>r.target[0]/r.target[1]);const xm=mean(x),ym=mean(y);const den=x.reduce((a,v)=>a+(v-xm)**2,0);const slope=den?x.reduce((a,v,i)=>a+(v-xm)*(y[i]-ym),0)/den:0;const intercept=ym-slope*xm;const predictions=rows.map(r=>{const p=(r.scores||[]).map(s=>{const mx=r.workMax?.[s[1]]||0;return mx>0?s[0]/mx:null}).filter(v=>v!==null);return p.length?r.target?null:Math.max(0,Math.min(1,intercept+slope*mean(p))):null}).filter(v=>v!==null);return {label,observed,model:predictions.length?{intercept,slope,predictions,examMax:mean(observed.map(r=>r.target[1]))}:null};}
function render(subject,year,group){const rows=state.rows;const all=rows.flatMap(r=>r.values);const avg=mean(all), med=median(all), completion=mean(rows.map(r=>r.values.length));const exam=forecastExam(rows); $('sectionTitle').textContent=`${subject} · ${group==='__all'?'все группы':group}`;$('recordCount').textContent=rows.length;$('meanValue').textContent=format(avg);$('medianValue').textContent=format(med);$('completionValue').textContent=format(completion);$('meanFoot').textContent=`${year} · ${all.length.toLocaleString('ru-RU')} оценок · шкала зависит от Quiz`;$('riskValue').textContent=exam.observed.length?format(mean(exam.observed.map(r=>r.target[0])))+' / '+format(mean(exam.observed.map(r=>r.target[1]))):'—';$('forecastBar').style.width=exam.model?'55%':'0%';$('riskChip').textContent=exam.model?'модель экзамена/зачёта':'нет модели';$('forecastTitle').textContent=exam.model?'Прогноз экзаменационной оценки':'Недостаточно данных для прогноза';$('forecastScore').textContent=exam.model?format(mean(exam.model.predictions)*exam.model.examMax):'—';$('forecastText').textContent=exam.model?`Целевая колонка: «${exam.label}». Модель использует порядок Quiz и среднюю долю набранных баллов от максимума каждой работы. Исторических экзаменационных оценок: ${exam.observed.length}; прогноз рассчитан для ${exam.model.predictions.length} студентов без целевой оценки.`:`Целевая экзаменационная/зачётная колонка не содержит минимум 10 наблюдений для устойчивой модели. Найденная колонка: «${exam.label}».`;$('activityInsight').textContent=`В выборке ${rows.length} студентов и ${all.length} доступных оценок. В среднем у студента есть ${format(completion)} Quiz с числовой оценкой; их порядок используется как временная последовательность.`;drawCharts(rows);renderRecs(completion,exam);renderTable(rows,exam);}
function drawCharts(rows){Object.values(state.charts).forEach(c=>c.destroy());const bins=[0,0,0],labels=['0–1 балл','1–2 балла','2+ балла'];rows.map(r=>mean(r.values)).forEach(v=>bins[v<=1?0:v<=2?1:2]++);state.charts.dist=new Chart($('distributionChart'),{type:'bar',data:{labels,datasets:[{data:bins,backgroundColor:['#6254d8','#a59af4','#75c89b'],borderRadius:6,barPercentage:.64}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:10}}},y:{beginAtZero:true,grid:{color:'#f0eff5'},ticks:{font:{size:10},precision:0}}}}});const count=rows.reduce((a,r)=>{r.values.forEach((_,i)=>a[i]=(a[i]||0)+1);return a},[]).slice(0,8);state.charts.activity=new Chart($('activityChart'),{type:'line',data:{labels:count.map((_,i)=>`Работа ${i+1}`),datasets:[{data:count,fill:true,tension:.4,borderColor:'#6254d8',backgroundColor:'rgba(98,84,216,.1)',pointBackgroundColor:'#6254d8',pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:9}}},y:{beginAtZero:true,grid:{color:'#f0eff5'},ticks:{font:{size:10},precision:0}}}}});}
function renderRecs(completion,exam){const rec=[['◷','Максимум каждой работы определяется по максимальному имеющемуся баллу этой колонки; значения не переводятся в общую шкалу 100.'],['↗','Quiz используется как порядок накопления: ранние неполные результаты не сравниваются напрямую с итогом семестра.'],['✓',exam.observed.length?`Для целевой колонки найдено ${exam.observed.length} экзаменационных/зачётных оценок. Прогноз относится к оценке экзамена/зачёта, а не к итоговой оценке курса.`:'В выбранном срезе пока недостаточно наблюдений по экзамену/зачёту для модели.']];$('recommendations').innerHTML=rec.map(([i,t])=>`<div class="recommendation"><span class="rec-icon">${i}</span><span>${esc(t)}</span></div>`).join('');}
function renderTable(rows,exam){$('studentTable').innerHTML=rows.slice(0,12).map((r,i)=>{const m=mean(r.values);const t=r.target?`${format(r.target[0])} / ${format(r.target[1])}`:'нет экзамена';return `<tr><td>${i+1}</td><td>${esc(r.group)}</td><td><b>${format(m)}</b></td><td>${r.values.length}</td><td><span class="status-pill ${r.target?'':'mid'}">${t}</span></td></tr>`}).join('');}
function init(){state.files=(window.DATA_MANIFEST||[]).map(parseFile);const subjects=[...new Set(state.files.map(f=>f.subject))];$('subjectSelect').innerHTML=subjects.map(s=>`<option>${esc(s)}</option>`).join('');$('subjectSelect').addEventListener('change',updateYears);$('yearSelect').addEventListener('change',updateGroups);$('loadButton').addEventListener('click',run);if(!state.files.length){setStatus('Манифест данных не найден.',true);return}updateYears();run();}
init();
